/**
 * GENERATED by scripts/fetch-dish-images.ts — do not edit by hand.
 *
 * Attribution for the dish photography, as a module rather than only a markdown
 * file, because CC BY-SA requires the credit to travel with the image where a
 * reader can see it. The dish page shows the author and licence; /credits lists
 * every photograph.
 */

export interface ImageCredit {
  dish: string;
  author: string;
  licence: string;
  source: string;
  licenceUrl: string | null;
}

export const IMAGE_CREDITS: readonly ImageCredit[] = [
  { dish: "Boondi raita", author: "Ravi Talwar", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Boondi_Raita.JPG", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Butter chicken", author: "stu_spivack", licence: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Chicken_makhani.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0" },
  { dish: "Butter naan", author: "Ganesh Mohan T", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Butter_Naan_2.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Chicken dum biryani", author: "Umesh Tongbra", licence: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Dum_Biryani_Plate.jpg", licenceUrl: "http://creativecommons.org/licenses/by-sa/3.0/" },
  { dish: "Dahi puri", author: "Panku00143", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Dahi_Puri_by_Jai_Ambe_Chaat_Bhandaar_in_Bhopal_Madhya_Pradesh.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Dal makhani", author: "Miansari66", licence: "CC0", source: "https://commons.wikimedia.org/wiki/File:Dal_Makhani..JPG", licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en" },
  { dish: "Fresh lime soda", author: "HARIOM.AWASTHI", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Neemboo-Paani_(Lime_Water).JPG", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Gajar ka halwa", author: "Sharvarism", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Delicious_Gajar_Ka_Halwa.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Garlic naan", author: "Joy", licence: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Garlic_naan_1.jpg", licenceUrl: "https://creativecommons.org/licenses/by/2.0" },
  { dish: "Gulab jamun", author: "Suyash.dwivedi", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Two_Gulab_Jamun_in_a_plate_01.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Hyderabadi mutton biryani", author: "User:Hyderabadi biryani", licence: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Hyderabadi_Biryani_2.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0" },
  { dish: "Jeera rice", author: "Marajozkee", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Jeera_rice.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Kadai prawns", author: "Aiswaryamenonp", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Prawns_Masala.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Kingfisher lager", author: "Bertrouf", licence: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Kingfisher_beer_bottle.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0" },
  { dish: "Kulfi falooda", author: "Aashita Kawatra", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Falooda_kulfi_from_India.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Laccha paratha", author: "Sonia Goyal", licence: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Lachha-paratha.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0" },
  { dish: "Mango lassi", author: "JIP", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Mango_lassi_at_restaurant_Momo_%26_More_in_March_2024.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Masala chai", author: "Miansari66", licence: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Masala_Chai.JPG", licenceUrl: null },
  { dish: "Masala papad", author: "Himanshu Agrawal 1998", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Onion_Masala_Papad.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Murgh malai tikka", author: "Renupradhul", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Chicken_Malai_Tikka.JPG", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Mutton seekh kebab", author: "Sumitmalhotra", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Seekh_Kebabs_on_Fire.JPG", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Palak paneer", author: "Daniel Zemans", licence: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Palak_Paneer_curry_on_plate.jpg", licenceUrl: "https://creativecommons.org/licenses/by/2.0" },
  { dish: "Paneer butter masala", author: "Gannu03", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Paneer_butter_masala_3.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Paneer tikka", author: "Sonja Pauen -Stanhopea", licence: "CC BY 2.0 de", source: "https://commons.wikimedia.org/wiki/File:Panir_Tikka_Indian_cheese_grilled.jpg", licenceUrl: "https://creativecommons.org/licenses/by/2.0/de/deed.en" },
  { dish: "Papdi chaat", author: "Sonia Goyal", licence: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Papdi-chaat.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0" },
  { dish: "Punjabi samosa", author: "Priyam1307", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Samosa_with_chutney.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
  { dish: "Rogan josh", author: "stu_spivack", licence: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Mutton_rogan_josh.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0" },
  { dish: "Tandoori prawns", author: "Goutamroykol", licence: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Tandoori_Prawn_-_Hotel_Lindsay_-_Kolkata_-_FILE_0008.jpg", licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0" },
];

const BY_DISH = new Map(IMAGE_CREDITS.map((c) => [c.dish, c]));

export function creditFor(dishName: string): ImageCredit | null {
  return BY_DISH.get(dishName) ?? null;
}
